name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Python 
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Build python library
        run: ./build

      - uses: actions/setup-node@v4

      - name: Build the react page
        working-directory: ./page
        run: |
          npm install
          npm run build
          tar cfvz ../github-pages.tar.gz build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
